# Generated by Django 4.1.2 on 2022-10-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('SummaArticles', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(verbose_name='Номер')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата документа')),
                ('summ_plan', models.FloatField(verbose_name='Сумма план')),
                ('date_plan', models.DateField(blank=True, null=True, verbose_name='Дата план')),
                ('summ_fact', models.FloatField(verbose_name='Сумма факт')),
                ('date_fact', models.DateField(blank=True, null=True, verbose_name='Дата факт')),
            ],
            options={
                'verbose_name': 'Платежи',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('plan', 'План'), ('fact', 'Факт')], default='approval', max_length=15, verbose_name='Тип платежа')),
                ('Сумма', models.FloatField(null=True)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('Document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Финансы',
                'verbose_name_plural': 'Финансы',
            },
        ),
        migrations.CreateModel(
            name='ExpensisInPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Сумма', models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True)),
                ('Сумма клиент', models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True)),
                ('Articles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.articles', verbose_name='Статья')),
                ('Document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.document', verbose_name='Документ')),
                ('Payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.payment', verbose_name='Платежи')),
            ],
            options={
                'verbose_name': 'Статья в платеже',
                'verbose_name_plural': 'Статьи в платеже',
            },
        ),
        migrations.CreateModel(
            name='ExpensisInDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summa', models.FloatField(blank=True, null=True, verbose_name='Сумма внутреннего учета')),
                ('Summaclient', models.FloatField(blank=True, null=True, verbose_name='Сумма для клиента')),
                ('Summatotal', models.FloatField(blank=True, null=True, verbose_name='Сумма итого')),
                ('Articles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.articles', verbose_name='Статья')),
                ('Document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Статья в документах',
                'verbose_name_plural': 'Статьи в документах',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True, verbose_name='Наименование клиента')),
                ('Phone', models.CharField(max_length=200, null=True, verbose_name='Телефон')),
                ('Email', models.EmailField(max_length=200, null=True, verbose_name='Email')),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата созания')),
                ('Address', models.CharField(max_length=200, null=True, verbose_name='Адресс юредический')),
                ('К/C', models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True)),
                ('Р/С', models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True)),
                ('ИНН', models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True)),
                ('КПП', models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True)),
                ('БИК', models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True)),
                ('Bank', models.CharField(max_length=200, null=True, verbose_name='Банк')),
                ('Addressk', models.CharField(max_length=200, null=True, verbose_name='Адресс корреспонденции')),
                ('Director', models.CharField(max_length=200, null=True, verbose_name='Директор')),
                ('file', models.FileField(blank=True, max_length=100000, null=True, upload_to='chapters/%Y/%m/%D', verbose_name='Договор')),
                ('Document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='Document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.document', verbose_name='Документ'),
        ),
    ]
