# Generated by Django 4.1.2 on 2022-11-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиент ЮР', 'verbose_name_plural': 'Клиенты ЮР'},
        ),
        migrations.RemoveField(
            model_name='expensisinpayment',
            name='Сумма',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='Сумма',
        ),
        migrations.AddField(
            model_name='document',
            name='SummaclientClient',
            field=models.FloatField(blank=True, null=True, verbose_name='Итого по сумме для клиента'),
        ),
        migrations.AddField(
            model_name='document',
            name='SummatotalArticles',
            field=models.FloatField(blank=True, null=True, verbose_name='Итого по сумме статьей'),
        ),
        migrations.AddField(
            model_name='expensisindocument',
            name='Unit',
            field=models.CharField(max_length=10, null=True, verbose_name='Ед.изм'),
        ),
        migrations.AddField(
            model_name='expensisindocument',
            name='Volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='expensisinpayment',
            name='Summa_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, max_length=30, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='finance',
            name='summa',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
