# Generated by Django 4.1.2 on 2022-11-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensisinpayment',
            name='Summa_total',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True, verbose_name='Сумма итого'),
        ),
    ]
