# Generated by Django 4.1.2 on 2022-11-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_expensisinpayment_summa_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensisinpayment',
            name='Сумма',
        ),
        migrations.RemoveField(
            model_name='expensisinpayment',
            name='Сумма клиент',
        ),
        migrations.AddField(
            model_name='expensisinpayment',
            name='Summa_total',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='expensisinpayment',
            name='Summa_total_client',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True, verbose_name='Сумма клиент'),
        ),
    ]
