# Generated by Django 4.1.2 on 2022-11-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_articles_options_alter_finance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ИНН',
        ),
        migrations.AddField(
            model_name='customer',
            name='Inn',
            field=models.IntegerField(max_length=10, null=True, verbose_name='ИНН'),
        ),
    ]
