# Generated by Django 4.1.2 on 2022-11-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_customer_инн_customer_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Inn',
            field=models.IntegerField(null=True, verbose_name='ИНН'),
        ),
    ]
