# Generated by Django 4.1.2 on 2022-11-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_customer_inn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='SummatotalArticles',
            new_name='Summa_total_Articles',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='SummaclientClient',
            new_name='Summa_total_Client',
        ),
    ]
