# Generated by Django 4.1.2 on 2022-11-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_summatotalarticles_document_summa_total_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Ks',
            field=models.IntegerField(null=True, verbose_name='К/C'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='БИК',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='КПП',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Р/С',
            field=models.IntegerField(null=True),
        ),
    ]
