# Generated by Django 4.1.2 on 2022-11-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_customer_бик_remove_customer_кпп_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Inn',
            field=models.IntegerField(max_length=10, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Kpp',
            field=models.IntegerField(max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ks',
            field=models.IntegerField(max_length=20, null=True, verbose_name='К/C'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Rs',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Р/С'),
        ),
    ]
