# Generated by Django 4.1.2 on 2022-11-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_customer_inn_alter_customer_kpp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Director',
            field=models.CharField(max_length=200, null=True, verbose_name='Фамилия И.О руководителя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Inn',
            field=models.IntegerField(null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Kpp',
            field=models.IntegerField(null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ks',
            field=models.IntegerField(null=True, verbose_name='К/C'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Rs',
            field=models.IntegerField(null=True, verbose_name='Р/С'),
        ),
    ]
