# Generated by Django 4.1.2 on 2022-11-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_customer_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_ip',
            options={'verbose_name': 'Клиент ИП', 'verbose_name_plural': 'Клиенты ИП'},
        ),
        migrations.CreateModel(
            name='Customer_fiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True, verbose_name='ФИО физического лица')),
                ('Phone', models.CharField(max_length=200, null=True, verbose_name='Телефон')),
                ('Email', models.EmailField(max_length=200, null=True, verbose_name='Email')),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата созания')),
                ('Address', models.CharField(max_length=200, null=True, verbose_name='Адрес регистрации')),
                ('Issued_by', models.CharField(max_length=200, null=True, verbose_name='Кем выдан паспорт')),
                ('Rs', models.IntegerField(null=True, verbose_name='Р/С')),
                ('Inn', models.IntegerField(null=True, verbose_name='ИНН')),
                ('Bik', models.IntegerField(null=True, verbose_name='БИК')),
                ('Bank', models.CharField(max_length=200, null=True, verbose_name='Банк')),
                ('Director', models.CharField(max_length=200, null=True, verbose_name='Фамилия И.О физического лица')),
                ('file', models.FileField(blank=True, max_length=100000, null=True, upload_to='chapters/%Y/%m/%D', verbose_name='Договор')),
                ('Document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Клиент Физ',
                'verbose_name_plural': 'Клиенты Физ',
            },
        ),
    ]
