# Generated by Django 4.1.2 on 2022-11-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_customer_ip_options_customer_fiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_fiz',
            name='Nomer',
            field=models.IntegerField(null=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='customer_fiz',
            name='Seria',
            field=models.IntegerField(null=True, verbose_name='Серия'),
        ),
    ]
