# Generated by Django 4.1.3 on 2022-11-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_customer_fiz_nomer_customer_fiz_seria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Bik',
            field=models.BigIntegerField(null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Inn',
            field=models.BigIntegerField(null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Kpp',
            field=models.BigIntegerField(null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ks',
            field=models.BigIntegerField(null=True, verbose_name='К/C'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Rs',
            field=models.BigIntegerField(null=True, verbose_name='Р/С'),
        ),
    ]
