# Generated by Django 4.1.3 on 2022-11-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_customer_bik_alter_customer_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_fiz',
            name='Bik',
            field=models.BigIntegerField(null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='customer_fiz',
            name='Inn',
            field=models.BigIntegerField(null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='customer_fiz',
            name='Nomer',
            field=models.BigIntegerField(null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='customer_fiz',
            name='Rs',
            field=models.BigIntegerField(null=True, verbose_name='Р/С'),
        ),
        migrations.AlterField(
            model_name='customer_fiz',
            name='Seria',
            field=models.BigIntegerField(null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='customer_ip',
            name='Bik',
            field=models.BigIntegerField(null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='customer_ip',
            name='Inn',
            field=models.BigIntegerField(null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='customer_ip',
            name='Ks',
            field=models.BigIntegerField(null=True, verbose_name='К/C'),
        ),
        migrations.AlterField(
            model_name='customer_ip',
            name='Ogrnip',
            field=models.BigIntegerField(null=True, verbose_name='ОГРН ИП'),
        ),
        migrations.AlterField(
            model_name='customer_ip',
            name='Rs',
            field=models.BigIntegerField(null=True, verbose_name='Р/С'),
        ),
    ]
