# Generated by Django 4.1.3 on 2022-12-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_customer_fiz_bik_alter_customer_fiz_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensisindocument',
            name='Summatotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Сумма итого'),
        ),
    ]
