# Generated by Django 4.1.3 on 2022-12-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_expensisindocument_summatotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensisindocument',
            name='Summatotal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=30, null=True, verbose_name='Сумма итого'),
        ),
        migrations.AlterField(
            model_name='expensisinpayment',
            name='Document',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.document', verbose_name='Документ'),
        ),
    ]
