# Generated by Django 4.1.3 on 2022-12-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_expensisindocument_summatotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Ед. изм'),
        ),
    ]
