# Generated by Django 4.1.3 on 2022-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_orderreport_articles_type_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreport',
            name='Name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название отчета'),
        ),
    ]
