# Generated by Django 4.1.2 on 2022-11-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_finance_options_payment_geeks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'справочник статей', 'verbose_name_plural': 'Справочник статьи'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='К/C',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='geeks',
        ),
        migrations.AddField(
            model_name='customer',
            name='Ks',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=30, null=True, verbose_name='К/C'),
        ),
        migrations.AlterField(
            model_name='expensisindocument',
            name='Unit',
            field=models.CharField(max_length=5, null=True, verbose_name='Ед.изм'),
        ),
    ]
